/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 30-oct.-2022 6:05:32 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Bache` CASCADE
;

DROP TABLE IF EXISTS `Consolidado` CASCADE
;

DROP TABLE IF EXISTS `Tipo_Usuario` CASCADE
;

DROP TABLE IF EXISTS `Usuario` CASCADE
;

/* Create Tables */

CREATE TABLE `Bache`
(
	`latitud` DECIMAL(9,6) NOT NULL COMMENT 'Atributo donde se almacena la latitud de la coordenada geografica correspondiente a la ubicacion del bache',
	`longitud` DECIMAL(9,6) NOT NULL COMMENT 'Atributo donde se almacena la longitud de la coordenada geografica correspondiente a la ubicacion del bache',
	`marca_tiempo` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT 'Marca de tiempo para creacion y actualizacion',
	`id_bache` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador unico del bache',
	`direccion` VARCHAR(50) NOT NULL COMMENT 'Atributo que almacena la ubicacion aproximada obtenida a partir del gps en el aplicativo movil',
	`metodo` VARCHAR(20) NOT NULL COMMENT 'Metodo de obtencion del bache: acelerometro o cnn (red neuronal convolucional)',
	`sistema_coordenadas` VARCHAR(20) NOT NULL COMMENT 'sistema geodEsico de coordenadas geograficas usado, WGS 84, EPSG:7458 (Magna Ciudad Bogota) u otros',
	`precision_gps` DECIMAL(4,2) NOT NULL COMMENT 'Precision del gps en metros.',
	`usuario` VARCHAR(50) NULL COMMENT 'FK a usuario que registró el bache',
	CONSTRAINT `PK_Punto` PRIMARY KEY (`id_bache` ASC)
)
COMMENT = 'Tabla correspondiente a los atributos de los baches obtenidos por medio del aplicativo movil'

;

CREATE TABLE `Consolidado`
(
	`id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del registro',
	`conteoRegistros` INT NOT NULL DEFAULT 0 COMMENT 'Conteo de registros generados',
	`usuario` VARCHAR(50) NULL,
	CONSTRAINT `PK_Registro_Reportes` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Tabla que almacena el conteo de reportes generados'

;

CREATE TABLE `Tipo_Usuario`
(
	`tipo` VARCHAR(50) NOT NULL COMMENT 'Tipo de usuario',
	`tipo_id` INT NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_Tipo` PRIMARY KEY (`tipo_id` ASC)
)
COMMENT = 'Tipo de usuario'

;

CREATE TABLE `Usuario`
(
	`usuario` VARCHAR(50) NOT NULL COMMENT 'Usuario del aplicativo',
	`contrasena` CHAR(80) NOT NULL COMMENT 'Contrasena encriptada',
	`tipo_id` INT NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`usuario` ASC)
)
COMMENT = 'Tabla que almacena los usuario del sistema'

;

/* Create Foreign Key Constraints */

ALTER TABLE `Bache` 
 ADD CONSTRAINT `FK_Bache_Usuario`
	FOREIGN KEY (`usuario`) REFERENCES `Usuario` (`usuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Consolidado` 
 ADD CONSTRAINT `FK_Consolidado_Usuario`
	FOREIGN KEY (`usuario`) REFERENCES `Usuario` (`usuario`) ON DELETE Restrict ON UPDATE Restrict
;


ALTER TABLE `Usuario` 
 ADD CONSTRAINT `FK_Usuario_Tipo_Usuario`
	FOREIGN KEY (`tipo_id`) REFERENCES `Tipo_Usuario` (`tipo_id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
